manifest:
  version: "0.12"

  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmk
      revision: main
      path: zmk

  self:
    path: .
