name: Build ZMK Firmware

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git cmake ninja-build gperf \
              ccache dfu-util device-tree-compiler wget xz-utils file

      # 3️⃣ Install west (Zephyr workspace manager)
      - name: Install west
        run: pip3 install west

      # 4️⃣ Initialize ZMK workspace using local manifest
      - name: Initialize ZMK workspace
        run: |
          west init -l .
          west update
          west zephyr-export

      # 5️⃣ Build mediapad3 firmware for nRF52840
      - name: Build mediapad3 firmware
        run: |
          west build -s zmk/app -d build/mediapad3 -b mediapad3 -- \
            -DZMK_CONFIG=$(pwd)/config

      # 6️⃣ Upload firmware artifact
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/mediapad3/zephyr/zmk.uf2
