name: Build ZMK Firmware

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/zmkfirmware/zmk-build-arm:stable

    steps:
      - name: Checkout configuration
        uses: actions/checkout@v4

      - name: Initialize west and fetch ZMK
        run: |
          west init -l .
          west update
          west zephyr-export

      - name: Build firmware for mediapad3
        run: |
          west build -s zmk/app -d build/mediapad3 -b mediapad3 -- \
            -DZMK_CONFIG=$(pwd)/config

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/mediapad3/zephyr/zmk.uf2
