name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull ZMK Docker image
        run: docker pull zmkfirmware/zephyr-west-action-arm:latest

      - name: Initialize workspace
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            init -m https://github.com/zmkfirmware/zmk.git -n .

      - name: Update workspace
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            update

      - name: Export Zephyr
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            zephyr-export

      - name: Build mediapad3 firmware
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            build -d build -p mediapad3

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
