name: Build mediapad3

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build mediapad3 firmware

    steps:
      # Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache modules to speed up builds
      - name: Cache ZMK and Zephyr modules
        uses: actions/cache@v3
        with:
          path: |
            modules/
            tools/
            zephyr/
            zmk/
          key: ${{ runner.os }}-zmk-${{ hashFiles('west.yml') }}
          restore-keys: |
            ${{ runner.os }}-zmk-

      # Initialize west workspace
      - name: Initialize west
        run: docker run --rm -v "${{ github.workspace }}:/workspace" zmkfirmware/zephyr-west-action-arm:latest init -l /workspace

      # Update west projects
      - name: Update west dependencies
        run: docker run --rm -v "${{ github.workspace }}:/workspace" zmkfirmware/zephyr-west-action-arm:latest update

      # Export Zephyr build environment
      - name: Zephyr export
        run: docker run --rm -v "${{ github.workspace }}:/workspace" zmkfirmware/zephyr-west-action-arm:latest zephyr-export

      # Build the firmware
      - name: Build mediapad3 firmware
        run: docker run --rm -v "${{ github.workspace }}:/workspace" zmkfirmware/zephyr-west-action-arm:latest build -s zmk/app -b mediapad3 -- -DSHIELD=mediapad3 -DZMK_CONFIG=/workspace/config

      # Display Kconfig for debugging
      - name: Show Kconfig
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      # Rename the UF2 file
      - name: Rename firmware file
        run: cp build/zephyr/zmk.uf2 mediapad3.uf2

      # Upload firmware as artifact
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: mediapad3.uf2
