name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull ZMK Docker image
        run: docker pull zmkfirmware/zephyr-west-action-arm:latest

      - name: Build mediapad3 firmware
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            /bin/sh -c "\
              set -e; \
              west init -m https://github.com/zmkfirmware/zmk.git -n .; \
              west update; \
              west zephyr-export; \
              west build -d build -p mediapad3 \
            "

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
