name: ZMK Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install pip packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Initialize west workspace
      run: |
        docker run --rm -v "${{ github.workspace }}:/workspace" \
          zmkfirmware/zephyr-west-action-arm:latest \
          init -m /workspace/west.yml -n /workspace

    - name: Update west dependencies
      run: |
        docker run --rm -v "${{ github.workspace }}:/workspace" \
          zmkfirmware/zephyr-west-action-arm:latest \
          update -r

    - name: Zephyr export
      run: |
        docker run --rm -v "${{ github.workspace }}:/workspace" \
          zmkfirmware/zephyr-west-action-arm:latest \
          zephyr-export

    - name: Build firmware
      run: |
        docker run --rm -v "${{ github.workspace }}:/workspace" \
          zmkfirmware/zephyr-west-action-arm:latest \
          build /workspace/app -b mediapad3

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: mediapad3-firmware
        path: app/build/mediapad3.uf2
