name: Build ZMK Firmware

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/zmkfirmware/zmk-build-arm:stable

    steps:
      - name: Checkout configuration
        uses: actions/checkout@v4

      - name: Initialize west
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -d build/left -b nrf52840_dongle -- \
            -DZMK_CONFIG=$(pwd)/config

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: build/left/zephyr/zmk.uf2
