name: ZMK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build firmware using the official ZMK Action
      - name: Build mediapad3 firmware
        uses: zmkfirmware/zmk-actions@v1
        with:
          board: mediapad3

      # 3. Upload the compiled firmware as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
