name: Build mediapad3 firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull ZMK Docker image
      run: docker pull zmkfirmware/zephyr-west-action-arm:latest

    - name: Initialize west workspace
      run: |
        docker run --rm -v "${{ github.workspace }}:/workspace" \
          zmkfirmware/zephyr-west-action-arm:latest \
          init -m /workspace/west.yml -n /workspace

    - name: Update west projects
      run: |
        docker run --rm -v "${{ github.workspace }}:/workspace" \
          zmkfirmware/zephyr-west-action-arm:latest \
          update -r

    - name: Export Zephyr environment
      run: |
        docker run --rm -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          zmkfirmware/zephyr-west-action-arm:latest \
          zephyr-export

    - name: Build firmware for mediapad3
      run: |
        docker run --rm -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          zmkfirmware/zephyr-west-action-arm:latest \
          build -p mediapad3 -d build

    - name: Upload built firmware
      uses: actions/upload-artifact@v4
      with:
        name: mediapad3-firmware
        path: build/zephyr/zmk.uf2
