on: [push, pull_request, workflow_dispatch]

name: Build MediPad3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        with:
          args: 'init "-l config"'

      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        with:
          args: 'update'

      - name: Build Firmware
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        with:
          args: 'build "-s zmk/app -b mediapad_nrf52840 -- -DSHIELD=mediapad3 -DZMK_CONFIG=/github/workspace/config"'

      - name: Rename output
        run: cp build/zephyr/zmk.uf2 mediapad3_nrf52840.uf2

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: mediapad3_nrf52840.uf2
