name: ZMK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull ZMK Docker image
        run: docker pull zmkfirmware/zephyr-west-action-arm:latest

      # Fix: Override the 'west' ENTRYPOINT with /bin/bash, then explicitly call 'west' subcommands.
      - name: Build mediapad3 firmware
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            -c " \ 
              # 1. Upgrade west to meet the ZMK requirement
              pip3 install west --upgrade && \
              # 2. Initialize the workspace
              west init -l . && \
              # 3. Download the dependencies (ZMK is cloned to 'zmk/', which contains the Zephyr submodule)
              west update -r && \
              # === DEBUG STEP: Check directory structure ===
              # This will show you the directory name where Zephyr was cloned.
              ls -F && \
              # =============================================
              # 4. Build the firmware: Set ZEPHYR_BASE to the expected path based on your west.yml
              #    (Your manifest puts ZMK at 'zmk/', and Zephyr is inside ZMK).
              export ZEPHYR_BASE=zmk/zephyr && \
              west build -d build -b mediapad3
            "

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
