name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Initialize West using local manifest
      - name: West Init
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            west init -l .

      # Update projects
      - name: West Update
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            west update -r

      # Zephyr export (sets up environment variables)
      - name: West Zephyr Export
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            west zephyr-export

      # Build firmware for mediapad3
      - name: Build Firmware
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            west build -p mediapad3 -d build

      # Upload built firmware artifact
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
