name: ZMK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull ZMK Docker image
        run: docker pull zmkfirmware/zephyr-west-action-arm:latest

      - name: Initialize, update and build ZMK
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            init -l . && \
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            update -r && \
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            zephyr-export && \
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            build -p mediapad3 -d build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
