name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Initialize west workspace
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest init -l .

      - name: Update west workspace
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest update -r

      - name: Zephyr export
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest zephyr-export

      - name: Build mediapad3 firmware
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest build -p mediapad3 -d build

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zephyr.hex
