name: ZMK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull ZMK Docker image
        run: docker pull zmkfirmware/zephyr-west-action-arm:latest

      - name: Build mediapad3 firmware
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            -c " \
              # 1. Upgrade west to meet the ZMK requirement
              pip3 install west --upgrade && \
              
              # 2. Initialize the workspace using the LOCAL west.yml file
              west init -l . && \
              
              # 3. Download the main ZMK repository
              west update && \
              
              # 4. Create the 'zmk' directory explicitly to prevent path errors
              mkdir -p zmk && \
              
              # 5. Explicitly clone ZMK submodules (Zephyr) for reliability
              git -C zmk submodule update --init --recursive && \
              
              # 6. Set ZEPHYR_BASE and build the firmware
              export ZEPHYR_BASE=zmk/zephyr && \
              west build -d build -b mediapad3
            "

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
