name: ZMK Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Build
        run: |
          echo "Using Docker for ZMK build"

      - name: Build mediapad3 firmware
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace \
          zmkfirmware/zephyr-west-action-arm:latest /bin/bash -c "
            set -e
            # Initialize ZMK workspace from official manifest
            west init -m https://github.com/zmkfirmware/zmk.git -n
            west update
            west zephyr-export
            # Build your custom board
            west build -d build -p mediapad3
          "

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
