name: ZMK Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build mediapad3 firmware
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            sh -c "
              set -e
              west init -l . &&
              west update -r &&
              west zephyr-export &&
              west build -p mediapad3 -d build
            "

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
