name: ZMK Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize ZMK workspace
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace \
          zmkfirmware/zephyr-west-action-arm:latest west init -m https://github.com/zmkfirmware/zmk.git -n

      - name: Update ZMK workspace
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace \
          zmkfirmware/zephyr-west-action-arm:latest west update

      - name: Zephyr export
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace \
          zmkfirmware/zephyr-west-action-arm:latest west zephyr-export

      - name: Build mediapad3 firmware
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace \
          zmkfirmware/zephyr-west-action-arm:latest west build -d build -p mediapad3

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
