name: Build mediapad3 Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build mediapad3

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Cache west/Zephyr modules (speeds up subsequent builds)
      - name: Cache West modules
        uses: actions/cache@v3
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # 3️⃣ Initialize ZMK / West
      - name: West Init
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        with:
          args: init -l .

      # 4️⃣ Update ZMK dependencies
      - name: West Update
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        with:
          args: update

      # 5️⃣ Export Zephyr configuration
      - name: West Zephyr Export
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        with:
          args: zephyr-export

      # 6️⃣ Build mediapad3 firmware
      - name: Build mediapad3 Firmware
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        with:
          args: build -b nrf52840 -- -DSHIELD=mediapad3 -DZMK_CONFIG=/github/workspace/boards/arm/mediapad3

      # 7️⃣ Rename output firmware
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 mediapad3_nrf52840.uf2

      # 8️⃣ Upload the firmware artifact
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: mediapad3_nrf52840.uf2
