name: Build mediapad3 Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build mediapad3

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Cache West/Zephyr modules
      - name: Cache West modules
        uses: actions/cache@v3
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # 3️⃣ Initialize West in the repository root
      - name: West Init
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        working-directory: /github/workspace
        with:
          args: init -l .

      # 4️⃣ Update West dependencies inside the workspace
      - name: West Update
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        working-directory: /github/workspace
        with:
          args: update

      # 5️⃣ Export Zephyr environment
      - name: West Zephyr Export
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        working-directory: /github/workspace
        with:
          args: zephyr-export

      # 6️⃣ Build mediapad3 firmware
      - name: Build mediapad3 Firmware
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        working-directory: /github/workspace
        with:
          args: build -b nrf52840 -- -DSHIELD=mediapad3 -DZMK_CONFIG=/github/workspace/boards/arm/mediapad3

      # 7️⃣ Rename output UF2 file
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 mediapad3_nrf52840.uf2

      # 8️⃣ Upload firmware artifact
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: mediapad3_nrf52840.uf2
