name: ZMK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull ZMK Docker image
        run: docker pull zmkfirmware/zephyr-west-action-arm:latest

      # Fix: Override the 'west' ENTRYPOINT with /bin/bash, then explicitly call 'west' subcommands.
      - name: Build mediapad3 firmware
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            -c " \
              # 1. Upgrade west to meet the ZMK requirement
              pip3 install --upgrade west && \
              # 2. Initialize the workspace
              west init -l . && \
              # 3. Download dependencies
              west update && \
              # 4. Source the Zephyr environment to ensure 'west build' is available
              source /opt/toolchains/zephyr-sdk/environment-setup.sh && \
              # 5. Build the firmware
              west build -d build -b mediapad3
            "

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
