name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initialize west workspace
      - name: West Init
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            init -l .

      # Update west projects
      - name: West Update
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            update -r

      # Zephyr export
      - name: West Zephyr Export
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            zephyr-export

      # Build firmware
      - name: Build Firmware
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            zmkfirmware/zephyr-west-action-arm:latest \
            build -p mediapad3 -d build

      # Upload firmware
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: mediapad3-firmware
          path: build/zephyr/zmk.uf2
